### PR TITLE
[DEV-5733] metrics prs jiragroups

### PR DESCRIPTION
**Pull request by gaetano-guerriero**
This change is [Reviewable](https://reviewable.io/reviews/athenianco/api-spec/150)

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
*[`openapi.yaml` line 4441 at r1](https://reviewable.io/reviews/athenianco/api-spec/150#-NMYWb64CHegcwGipKhD:-NMYWb64CHegcwGipKhE:b45h) ([raw file](https://github.com/athenianco/api-spec/blob/db920bae84a5a6c6a2df79857c8f8160e7db0dd9/openapi.yaml#L4441)):*
> ```YAML
>         jiragroups:
>           description: |
>             Calculate metrics separately for each Jira Filter in the list.
> ```





_Code quote (i):_
```YAML
Calculate metrics separately for each Jira Filter in the list.
```



_Code snippet (ii):_
```YAML
Calculate metrics separately for each JIRA filter in the list.
```

**Review by vmarkovtsev — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/athenianco/api-spec/150)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gaetano-guerriero)

**Review by gaetano-guerriero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/athenianco/api-spec/150)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @vmarkovtsev)

___
*[`openapi.yaml` line 4441 at r1](https://reviewable.io/reviews/athenianco/api-spec/150#-NMYWb64CHegcwGipKhD:-NMYZYNr742T4Je_AeYY:b-b5cu39) ([raw file](https://github.com/athenianco/api-spec/blob/db920bae84a5a6c6a2df79857c8f8160e7db0dd9/openapi.yaml#L4441)):*
> ```YAML
>         jiragroups:
>           description: |
>             Calculate metrics separately for each Jira Filter in the list.
> ```

Fun fact: they changed the official spelling to Jira 
https://community.atlassian.com/t5/Jira-Software-questions/Which-is-the-correct-spelling-JIRA-or-Jira/qaq-p/765863#:~:text=it%20was%20originally%20JIRA%20but%20now%20officially%20Jira.

I noticed this because their auto-completion on the app was stubbornly changing jira => Jira.
Since we use anyway JIRA I guess we can continue with that

**Comment by vmarkovtsev** [comment]
*[`openapi.yaml` line 4441 at r1](https://reviewable.io/reviews/athenianco/api-spec/150#-NMYWb64CHegcwGipKhD:-NMYf3CK-ypIpCru6bwU:b-kl5b0r) ([raw file](https://github.com/athenianco/api-spec/blob/db920bae84a5a6c6a2df79857c8f8160e7db0dd9/openapi.yaml#L4441)):*
<details><summary><i>Previously, gaetano-guerriero wrote…</i></summary><blockquote>

Fun fact: they changed the official spelling to Jira 
https://community.atlassian.com/t5/Jira-Software-questions/Which-is-the-correct-spelling-JIRA-or-Jira/qaq-p/765863#:~:text=it%20was%20originally%20JIRA%20but%20now%20officially%20Jira.

I noticed this because their auto-completion on the app was stubbornly changing jira => Jira.
Since we use anyway JIRA I guess we can continue with that
</blockquote></details>

Jeez I am so old

**Review by akbarik — APPROVED** [review]

**Pull request merged**
